version: '2.4'

services:

  kowl:
    image: quay.io/cloudhut/kowl:sisv3
    container_name: kowl
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - "KOWL_GIT_SHA=8a5700c5141cac9f1b7e300008daec5d3df6187d"
        - "KOWL_GIT_REF=sisv3"
        - "KOWL_TIMESTAMP=1655301093"
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
    volumes:
      - ./kowl.yaml:/etc/kowl/config.yaml
    ports:
      - "9000:9000"

  kowl_production:
    image: quay.io/cloudhut/kowl:sisv3_production
    container_name: kowl_production
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - "KOWL_GIT_SHA=8a5700c5141cac9f1b7e300008daec5d3df6187d"
        - "KOWL_GIT_REF=sisv3"
        - "KOWL_TIMESTAMP=1655301093"
        - "PRODUCTION=true"
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
    volumes:
      - ./kowl.yaml:/etc/kowl/config.yaml
    ports:
      - "9001:9000"
