version: '2.4'

services:

  kowl:
    image: quay.io/cloudhut/kowl:sisv3
    container_name: kowl
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - "KOWL_GIT_SHA=5ff6e3c4dea98737b661186519eb310f2a898d06"
        - "KOWL_GIT_REF=sisv3"
        - "KOWL_TIMESTAMP=1649245410"
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
    volumes:
      - ./kowl.yaml:/etc/kowl/config.yaml
    ports:
      - "9000:9000"
